# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sparse_divide_out_size_factor_impl <- function(x, p, s) {
    .Call(`_transformGamPoi_sparse_divide_out_size_factor_impl`, x, p, s)
}

